# Generated by Django 4.1.7 on 2023-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacolumn",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="dataschema",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dataschema",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
