# Generated by Django 4.1.7 on 2023-03-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("src", "0002_datacolumn_create_datetime_datacolumn_last_update_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datacolumn",
            old_name="order",
            new_name="оrder_index",
        ),
        migrations.RemoveField(
            model_name="datacolumn",
            name="data_type",
        ),
        migrations.RemoveField(
            model_name="datacolumn",
            name="extra_args",
        ),
        migrations.RemoveField(
            model_name="datacolumn",
            name="schema",
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="column_type",
            field=models.CharField(
                choices=[
                    ("full_name", "Full Name"),
                    ("job", "Job"),
                    ("email", "Email"),
                    ("domain_name", "Domain Name"),
                    ("phone_number", "Phone Number"),
                    ("company_name", "Company Name"),
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("address", "Address"),
                    ("date", "Date"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="data_schema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="src.dataschema",
            ),
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="range_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="range_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datacolumn",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dataschema",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
