# Generated by Django 4.1.7 on 2023-03-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0006_remove_datacolumn_data_schema_datacolumn_data_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacolumn",
            name="data_schema",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datacolumn",
                to="src.dataschema",
                verbose_name="Data Schema",
            ),
        ),
    ]
