# Generated by Django 4.1.7 on 2023-03-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0008_dataschema_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataschema",
            name="status",
        ),
    ]
